# Generated by Django 4.1.7 on 2023-03-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(max_length=1500, verbose_name='İçerik')),
                ('image', models.FileField(upload_to=None, verbose_name='')),
                ('active', models.BooleanField(verbose_name='Göster')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
            ],
        ),
    ]
