# Generated by Django 4.1.7 on 2023-03-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('text', models.TextField(max_length=1500, verbose_name='Mesaj')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.card', verbose_name='Ürün')),
            ],
        ),
    ]
